{% set name = "kgen" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ba52d5709518dd3dd44b8d8d05603979e9a792c576080ff07f7c5e5ff63f1384

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.21.5
    - pymyami ==2.1.1

test:
  imports:
    - kgen
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/PalaeoCarb/Kgen
  summary: Python functions for calculating stoichiometric speciation constants for seawater.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
