{% set name = "kgen" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Kgen-{{ version }}.tar.gz
  sha256: 8b280ccc42113cec8c1a3b6ca493fc499fccc6b1fca72031a803639a00390689

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy >=1.21.5
    - pymyami ==2.1.0

test:
  imports:
    - kgen
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/PalaeoCarb/Kgen
  summary: Python functions for calculating stoichiometric speciation constants for seawater.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
